spring.application.name=practice

# Enable the H2 Web Console in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Fix the database name so it doesn't change randomly every restart
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sakshi
spring.datasource.password=Sak13@31

# (Optional) Print SQL statements in your terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true